version: "3.1"

services:
  db:
    image: postgres:12-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
  ws:
    image: diogob/postgres-websockets
    environment:
      PGWS_DB_URI: postgres://postgres:secret@db:5432/postgres
      PGWS_JWT_SECRET: "auwhfdnskjhewfi34uwehdlaehsfkuaeiskjnfduierhfsiweskjcnzeiluwhskdewishdnpwe"
      PGWS_ROOT_PATH: /home/postgres-websockets/client-example
      PGWS_LISTEN_CHANNEL: "pgws_socket"
    ports:
        - "8080:3000"
    depends_on:
        - db